In [38]:
import numpy
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.svm import SVC
import joblib


In [5]:
from sklearn.datasets import load_iris

In [6]:
data = load_iris()

In [7]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [9]:
pd.DataFrame(data.data)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [10]:
pd.DataFrame(data.data, columns=data.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [14]:
df['target'] = data.target

In [15]:
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [16]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
df['target_names'] = df['target'].map({i:name for i , name in enumerate(data.target_names)})

In [23]:
df

sepal length (cm)  sepal width (cm)  ...  target  target_names
0                  5.1               3.5  ...       0        setosa
1                  4.9               3.0  ...       0        setosa
2                  4.7               3.2  ...       0        setosa
3                  4.6               3.1  ...       0        setosa
4                  5.0               3.6  ...       0        setosa
..                 ...               ...  ...     ...           ...
145                6.7               3.0  ...       2     virginica
146                6.3               2.5  ...       2     virginica
147                6.5               3.0  ...       2     virginica
148                6.2               3.4  ...       2     virginica
149                5.9               3.0  ...       2     virginica

[150 rows x 6 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [26]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [27]:
df.describe()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)      target
count         150.000000        150.000000  ...        150.000000  150.000000
mean            5.843333          3.057333  ...          1.199333    1.000000
std             0.828066          0.435866  ...          0.762238    0.819232
min             4.300000          2.000000  ...          0.100000    0.000000
25%             5.100000          2.800000  ...          0.300000    0.000000
50%             5.800000          3.000000  ...          1.300000    1.000000
75%             6.400000          3.300000  ...          1.800000    2.000000
max             7.900000          4.400000  ...          2.500000    2.000000

[8 rows x 5 columns]

In [28]:
df['target_names'].value_counts()

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [30]:
#FOR BINARY CLASSS CLASSIFICATIONS//.scenario //1

binary_df = df[df['target'] !=2]

In [31]:
binary_df

sepal length (cm)  sepal width (cm)  ...  target  target_names
0                 5.1               3.5  ...       0        setosa
1                 4.9               3.0  ...       0        setosa
2                 4.7               3.2  ...       0        setosa
3                 4.6               3.1  ...       0        setosa
4                 5.0               3.6  ...       0        setosa
..                ...               ...  ...     ...           ...
95                5.7               3.0  ...       1    versicolor
96                5.7               2.9  ...       1    versicolor
97                6.2               2.9  ...       1    versicolor
98                5.1               2.5  ...       1    versicolor
99                5.7               2.8  ...       1    versicolor

[100 rows x 6 columns]

In [35]:
x_binary = binary_df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]

In [36]:
y_binary = binary_df['target']

In [54]:
x_train,x_test, y_train, y_test  = train_test_split(x_binary, y_binary, test_size=.2)

In [55]:
x_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
54                6.5               2.8                4.6               1.5
91                6.1               3.0                4.6               1.4
34                4.9               3.1                1.5               0.2
12                4.8               3.0                1.4               0.1
88                5.6               3.0                4.1               1.3
..                ...               ...                ...               ...
94                5.6               2.7                4.2               1.3
60                5.0               2.0                3.5               1.0
58                6.6               2.9                4.6               1.3
0                 5.1               3.5                1.4               0.2
24                4.8               3.4                1.9               0.2

[80 rows x 4 columns]

In [56]:
x_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
83                6.0               2.7                5.1               1.6
19                5.1               3.8                1.5               0.3
87                6.3               2.3                4.4               1.3
8                 4.4               2.9                1.4               0.2
38                4.4               3.0                1.3               0.2
4                 5.0               3.6                1.4               0.2
55                5.7               2.8                4.5               1.3
43                5.0               3.5                1.6               0.6
33                5.5               4.2                1.4               0.2
86                6.7               3.1                4.7               1.5
59                5.2               2.7                3.9               1.4
65                6.7               3.1                4.4               1.4
23                5.1               3.3                1.7               0.5
2                 4.7               3.2                1.3               0.2
80                5.5               2.4                3.8               1.1
93                5.0               2.3                3.3               1.0
96                5.7               2.9                4.2               1.3
20                5.4               3.4                1.7               0.2
95                5.7               3.0                4.2               1.2
26                5.0               3.4                1.6               0.4

In [57]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [58]:
x_test = scaler.transform(x_test)

In [44]:
x_train

array([[-1.33981886,  0.66433954, -1.01949153, -0.90459986],
       [ 0.30688588, -0.17593181,  0.8931224 ,  0.7115587 ],
       [ 0.45658631, -1.01620317,  0.75650712,  0.7115587 ],
       [ 0.45658631,  1.92474657, -1.15610681, -1.08417304],
       [ 0.75598718, -1.85647452,  0.75650712,  0.35241235],
       [ 0.00748502, -1.22627101,  0.75650712,  0.89113187],
       [ 0.30688588, -1.01620317,  0.41496891,  0.35241235],
       [-1.19011843,  0.24420386, -1.08779917, -1.08417304],
       [ 0.00748502, -1.01620317,  1.02973768,  0.7115587 ],
       [ 0.15718545, -0.17593181,  0.82481476,  0.89113187],
       [ 0.90568761, -0.38599965,  1.2346606 ,  1.07070505],
       [ 0.60628675, -0.17593181,  0.8931224 ,  1.25027822],
       [ 0.90568761, -0.59606749,  1.2346606 ,  0.7115587 ],
       [ 0.75598718, -0.38599965,  1.09804532,  1.25027822],
       [ 0.75598718,  0.66433954,  1.09804532,  1.42985139],
       [-1.63921972, -0.38599965, -1.01949153, -1.08417304],
       [-0.74101713,  0.

In [59]:
x_test

array([[ 0.80447849, -0.84955592,  1.5491294 ,  1.43557872],
       [-0.60826423,  1.46502368, -0.9391543 , -0.84381345],
       [ 1.27539273, -1.69122123,  1.06529646,  0.90956515],
       [-1.70706412, -0.42872327, -1.00827329, -1.01915131],
       [-1.70706412, -0.21830694, -1.07739228, -1.01915131],
       [-0.76523564,  1.04419103, -1.00827329, -1.01915131],
       [ 0.33356425, -0.6391396 ,  1.13441545,  0.90956515],
       [-0.76523564,  0.8337747 , -0.8700353 , -0.31779987],
       [ 0.01962143,  2.30668899, -1.00827329, -1.01915131],
       [ 1.90327839, -0.00789061,  1.27265343,  1.26024086],
       [-0.45129281, -0.84955592,  0.7197015 ,  1.08490301],
       [ 1.90327839, -0.00789061,  1.06529646,  1.08490301],
       [-0.60826423,  0.41294204, -0.80091631, -0.49313773],
       [-1.23614988,  0.20252572, -1.07739228, -1.01915131],
       [ 0.01962143, -1.48080491,  0.65058251,  0.55888943],
       [-0.76523564, -1.69122123,  0.30498755,  0.38355157],
       [ 0.33356425, -0.

In [60]:
svm_binary = SVC(kernel='linear',C=1.0,probability=True)

In [61]:
svm_binary.fit(x_train,y_train)

SVC(kernel='linear', probability=True)

In [62]:
svm_binary.predict(x_test)

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0])

In [63]:
classification_report(y_test, svm_binary.predict(x_test) )

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        10\n           1       1.00      1.00      1.00        10\n\n    accuracy                           1.00        20\n   macro avg       1.00      1.00      1.00        20\nweighted avg       1.00      1.00      1.00        20\n'

In [65]:
print('Report \n',classification_report(y_test, svm_binary.predict(x_test) )  )

Report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [ ]:
confusion_matrix(y_test, svm_binary.predict(x_test))

array([[10,  0],
       [ 0, 10]])

In [69]:
joblib.dump(svm_binary,'svm_binary.pkl')

['svm_binary.pkl']

In [113]:
import pickle
def load_model(user_data):
    model = joblib.load('svm_binary.pkl')
    predit = model.predict(user_data)
    return predit

load_model([[0.80447849, -0.84955592,  1.5491294 ,  1.43557872]])

array([1])

In [70]:
# multi class classifications

In [74]:
x_multi = df.drop(columns=['target', 'target_names'])

In [72]:
x_multi

sepal length (cm)  sepal width (cm)  ...  target  target_names
0                  5.1               3.5  ...       0        setosa
1                  4.9               3.0  ...       0        setosa
2                  4.7               3.2  ...       0        setosa
3                  4.6               3.1  ...       0        setosa
4                  5.0               3.6  ...       0        setosa
..                 ...               ...  ...     ...           ...
145                6.7               3.0  ...       2     virginica
146                6.3               2.5  ...       2     virginica
147                6.5               3.0  ...       2     virginica
148                6.2               3.4  ...       2     virginica
149                5.9               3.0  ...       2     virginica

[150 rows x 6 columns]

In [75]:
y_multi = df['target']

In [76]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [77]:
x_train_multi, x_test_multi, y_train_multi, y_test_multi =  train_test_split(x_multi,y_multi,test_size=.2)

In [78]:
x_train_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
116                6.5               3.0                5.5               1.8
17                 5.1               3.5                1.4               0.3
106                4.9               2.5                4.5               1.7
125                7.2               3.2                6.0               1.8
21                 5.1               3.7                1.5               0.4
..                 ...               ...                ...               ...
75                 6.6               3.0                4.4               1.4
64                 5.6               2.9                3.6               1.3
41                 4.5               2.3                1.3               0.3
142                5.8               2.7                5.1               1.9
15                 5.7               4.4                1.5               0.4

[120 rows x 4 columns]

In [79]:
y_train_multi

116    2
17     0
106    2
125    2
21     0
      ..
75     1
64     1
41     0
142    2
15     0
Name: target, Length: 120, dtype: int64

In [80]:
svm_multi = SVC(kernel='linear',C=1)

In [82]:
svm_multi.fit(x_train_multi,y_train_multi)

SVC(C=1, kernel='linear')

In [83]:
svm_multi.predict(x_test_multi)

array([1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2,
       0, 0, 2, 0, 1, 2, 1, 0])

In [101]:
joblib.dump(svm_multi,'svm_multiClassPredit.pkl')

['svm_multiClassPredit.pkl']

In [87]:
# Logistics regressions

from sklearn.linear_model import LogisticRegression

In [88]:
x_train

array([[ 1.58933556, -0.6391396 ,  1.20353444,  1.26024086],
       [ 0.96144991, -0.21830694,  1.20353444,  1.08490301],
       [-0.92220705, -0.00789061, -0.9391543 , -1.01915131],
       [-1.07917847, -0.21830694, -1.00827329, -1.19448917],
       [ 0.17659284, -0.21830694,  0.85793948,  0.90956515],
       [-0.13734999,  1.67544001, -0.80091631, -0.66847559],
       [ 0.96144991, -0.6391396 ,  1.27265343,  0.73422729],
       [ 0.01962143, -1.05997225,  1.06529646,  0.73422729],
       [-1.07917847, -0.00789061, -0.8700353 , -1.01915131],
       [-1.39312129,  0.62335837, -1.00827329, -0.84381345],
       [ 0.96144991, -0.6391396 ,  0.78882049,  0.90956515],
       [-0.92220705, -0.00789061, -0.9391543 , -1.19448917],
       [ 2.0602498 , -0.6391396 ,  1.34177242,  1.08490301],
       [-1.86403553, -0.21830694, -1.21563026, -1.19448917],
       [ 0.01962143, -1.48080491,  0.58146352,  0.38355157],
       [-0.13734999,  1.67544001, -1.07739228, -0.66847559],
       [ 0.64750708, -0.

In [89]:
x_test

array([[ 0.80447849, -0.84955592,  1.5491294 ,  1.43557872],
       [-0.60826423,  1.46502368, -0.9391543 , -0.84381345],
       [ 1.27539273, -1.69122123,  1.06529646,  0.90956515],
       [-1.70706412, -0.42872327, -1.00827329, -1.01915131],
       [-1.70706412, -0.21830694, -1.07739228, -1.01915131],
       [-0.76523564,  1.04419103, -1.00827329, -1.01915131],
       [ 0.33356425, -0.6391396 ,  1.13441545,  0.90956515],
       [-0.76523564,  0.8337747 , -0.8700353 , -0.31779987],
       [ 0.01962143,  2.30668899, -1.00827329, -1.01915131],
       [ 1.90327839, -0.00789061,  1.27265343,  1.26024086],
       [-0.45129281, -0.84955592,  0.7197015 ,  1.08490301],
       [ 1.90327839, -0.00789061,  1.06529646,  1.08490301],
       [-0.60826423,  0.41294204, -0.80091631, -0.49313773],
       [-1.23614988,  0.20252572, -1.07739228, -1.01915131],
       [ 0.01962143, -1.48080491,  0.65058251,  0.55888943],
       [-0.76523564, -1.69122123,  0.30498755,  0.38355157],
       [ 0.33356425, -0.

In [90]:
logistics_binary = LogisticRegression()
logistics_binary.fit(x_train,y_train)

LogisticRegression()

In [91]:
logistics_binary.predict(x_test)

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0])

In [92]:
print('classification_report' , classification_report(y_test, logistics_binary.predict(x_test)))

classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [93]:
joblib.dump(logistics_binary, 'LogisticsBinary.pkl')

['LogisticsBinary.pkl']

In [94]:
logistics_ovr = LogisticRegression(multi_class='ovr', solver='lbfgs',max_iter=2000)

In [95]:
logistics_ovr.fit(x_train_multi,y_train_multi)

c:\Users\lenovo T480\OneDrive\Desktop\DS\EURON\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='ovr')

In [96]:
logistics_ovr.predict(x_test_multi)

array([1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2,
       0, 0, 2, 0, 1, 2, 1, 0])

In [102]:
joblib.dump(logistics_ovr,'LogisticsMultiClass.pkl')

['LogisticsMultiClass.pkl']

In [99]:
print('classification_report for OVR \n' , classification_report(y_test_multi, logistics_ovr.predict(x_test_multi)))

classification_report for OVR 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.91      0.95        11
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [100]:
confusion_matrix(y_test_multi, logistics_ovr.predict(x_test_multi))

array([[11,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  8]])